### ISSUE TITLE
AsyncIpc seems to be broken on devel for Windows

### ISSUE THREAD

**Issue by PMunch** [cheatfate/asynctools#43]
Found during the CI for nimlsp: https://github.com/PMunch/nimlsp/actions/runs/3807847256/jobs/6477921305#step:7:438

**Comment by AmjadHD** [comment]
@PMunch That link has expired. Do you mean this error ?
`C:\Users\User\.nimble\pkgs\asynctools-0.1.1\asynctools\asyncipc.nim(190, 40) Error: expression cannot be cast to 'pointer'`
