### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by blark** [cheatfate/asynctools#5]
Hi, first of all, thanks so much for this. Is there any chance you can add examples? Specifically, I'm eager to try the async DNS resolver. I'm a noob to Nim and it would help! 

**edit**
Well, I read through the code and found a bit of an example at the end:

```
echo "=== asynchronous variant"

var aiList = waitFor(asyncGetAddrInfo("www.google.com", Port(80), domain = Domain.AF_INET))
```

What's with the "Port(80)" in there? I guess I'm a bit confused because I'm not sure what the HTTP port has to do with a DNS request. 

Also when I run that code I get: 

```
Error: ambiguous call; both nativesockets.ntohs(x: uint16)[declared in lib/pure/nativesockets.nim(269, 5)] and posix.ntohs(a1: uint16)[declared in lib/posix/posix.nim(122, 5)] match for: (uint16)
```

**Comment by cheatfate** [comment]
This `Port` argument was added to stay compatible with synchronous `getAddrInfo` procedure declared here:
https://github.com/nim-lang/Nim/blob/devel/lib/pure/nativesockets.nim#L222

This `Port` is not used in DNS request actually, but used to form up result array of returned addresses. If you don't care about, or don't know, please use `Port(0)`.

This is simple example for `server side`:

```nim
var server_socket = create_server_socket()

var aiList = getAddrInfo("0.0.0.0", Port(13337))
if bindAddr(server_socket, aiList.ai_addr,
            aiList.ai_addrlen.Socklen) < 0'i32:
  freeAddrInfo(aiList)
  raiseOSError(osLastError())
```

As you can see you can easily pass `aiList` to `bindAddr` and your server will setup on `0.0.0.0:13337`.

**Comment by cheatfate** [comment]
Compilation error, you mentioned got fixed.

**Comment by blark** [comment]
Hi, thank you very much for the quick response! I have managed to get it working, but I can't make the jump from Python's asyncio to Nim in my head. Sorry for being thick here! I was wondering if you would be willing to help. I have a very simple example of what I am trying to do in some pseudo-code that isn't working:

```
import asyncdispatch
import asynctools/asyncdns


proc lookup(n: string) {.async.} =
  return await asyncGetAddrInfo(n, Port(0))

proc callback(f: Future) =
   echo("$1 resolved to ip $2".format(f.domain, f.ip))

proc main() {.async.} =
  let domains = @["www.google.ca", "www.microsoft.com", "www.apple.com"]
  var answers = @[]

  for domain in domains:
    lookup(domain)
    # add callback?

waitFor main()
```

I have Googled around quite a bit and I can't seem to figure it out. Again, thanks so much!

**Comment by blark** [comment]
For anyone else that has the same questions as me I'll continue this thread. This code works but doesn't do exactly what I want:

```
import asyncdispatch
import asynctools/asyncdns


proc lookup(n: string) {.async.} =
  var response = await asyncGetAddrInfo(n, Port(0))
  echo(response)

proc main() {.async.} =
  let domains = @["www.google.ca", "www.microsoft.com", "www.apple.com"]
  var futures = newSeq[Future[void]]()
  for domain in domains:
    futures.add(lookup(domain))
  await all futures

waitFor main()
``` 

Instead of echoing the response I'd like to be able to set it and deal with it in a callback. Not 100% sure how to do this yet, or how to access the original request domain name.
