### ISSUE TITLE
Multiple A records for one name

### ISSUE THREAD

**Issue by blark** [cheatfate/asynctools#6]
Regarding asycdns, I have noticed that it only returns one IP regardless of how many A records there are for a name. Here is an example...
```
$ dig autodiscover.outlook.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> autodiscover.outlook.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3053
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;autodiscover.outlook.com.      IN      A

;; ANSWER SECTION:
autodiscover.outlook.com. 47    IN      CNAME   autodiscover.geo.outlook.com.
autodiscover.geo.outlook.com. 42 IN     CNAME   autodiscover.outlook.com.g.outlook.com.
autodiscover.outlook.com.g.outlook.com. 42 IN CNAME autodiscover-nameast3.outlook.com.
autodiscover-nameast3.outlook.com. 42 IN A      40.97.126.40
autodiscover-nameast3.outlook.com. 42 IN A      40.97.160.24
autodiscover-nameast3.outlook.com. 42 IN A      40.97.100.56
autodiscover-nameast3.outlook.com. 42 IN A      40.97.134.200
autodiscover-nameast3.outlook.com. 42 IN A      40.97.176.24
autodiscover-nameast3.outlook.com. 42 IN A      40.97.180.8
autodiscover-nameast3.outlook.com. 42 IN A      40.97.176.8
autodiscover-nameast3.outlook.com. 42 IN A      40.97.24.24
autodiscover-nameast3.outlook.com. 42 IN A      40.97.130.56
autodiscover-nameast3.outlook.com. 42 IN A      40.97.92.40

...SNIP...
```
When I use asyncdns I get this response:
```
autodiscover.outlook.com
ai_flags = 0x00000000
ai_family = 0x00000002
ai_socktype = 0x00000001
ai_protocol = 0x00000006
ai_canonname = 0x0000000000000000
ai_addrlen = 16
ai_addr = 0x00007FC3727B72B8
  sin_family = 0x0002
  sin_port = 0x0000 (0)
  sin_addr = 40.97.160.24
```
The IP returned is for autodiscover-nameast.outlook.com (40.97.166.24). Is there any way to get a seq with the actual A records that the CNAMEs resolve to? Note: this is true even if I attempt to resolve autodiscover-nameast3.outlook.com directly...

```autodiscover-nameast3.outlook.com
ai_flags = 0x00000000
ai_family = 0x00000002
ai_socktype = 0x00000001
ai_protocol = 0x00000006
ai_canonname = 0x0000000000000000
ai_addrlen = 16
ai_addr = 0x00007FCEC0FB8228
  sin_family = 0x0002
  sin_port = 0x0000 (0)
  sin_addr = 40.97.92.40
```

**Comment by cheatfate** [comment]
```nim
import asyncdispatch, asyncdns, os, nativesockets, strutils

when defined(windows):
  import winlean
else:
  import posix

when isMainModule:
  var aiList = waitFor(asyncGetAddrInfo("autodiscover-nameast.outlook.com",
                                        Port(80),
                                        domain = Domain.AF_INET))
  var ait = cast[ptr AddrInfo](aiList)
  while not ait.isNil:
    var address = newString(128)
    if ait.ai_family == toInt(Domain.AF_INET6):
      let p = cast[ptr Sockaddr_in6](ait.ai_addr)
      discard inet_ntop(ait.ai_family, cast[pointer](addr p.sin6_addr),
                        cstring(address), len(address).int32)
    else:
      let p = cast[ptr Sockaddr_in](ait.ai_addr)
      discard inet_ntop(ait.ai_family, cast[pointer](addr p.sin_addr),
                        cstring(address), len(address).int32)

    echo address
    ait = cast[ptr AddrInfo](cast[ptr AddrInfo](ait).ai_next)
```

**Comment by cheatfate** [comment]
Actually `asyncdns` was created to perform simple tasks (e.g. resolve `A` and `AAAA` records, its what original synchronous `getaddrinfo()` doing). So `CNAME` records are not supported.

**Comment by cheatfate** [comment]
@blark, any comments?

**Comment by blark** [comment]
Hi, I guess I have a couple. As you probably gathered I'm new to Nim so I have to run that code to see what it does. I see that it does a request, and then echos the IP address result, I'm just not sure how it differs from other examples. Any chance you could give me a quick sentence on what it's doing?

I was looking for a more complete resolver, so now I'm looking at trying to use c-ares from Nim. It's a task that's beyond my current skill set though, so I am going to have to do some learning ;)

**Comment by cheatfate** [comment]
@blark, it shows you all resolved addresses (by iterating over `ai_next` field of `AddInfo` structure), not only one.

**Comment by cheatfate** [comment]
@blark, you can create any type of resolver using my code, my current functions just using A/AAAA, but providers i'm using can resolve any kind of information.

**Comment by blark** [comment]
I don't know anything about the struct (it's a stuct right?) that you are getting the data from, I guess I have to look into the docs for this thing. I see in the '$' function how you are pulling info out of it but it's still not super clear to me being such a noob. Thanks for the help. 

Is there any reason you aren't exposing the lookup data in some sort of object so it's easier to access? Something where you could just make a request and then do `echo response.ip`? Again thanks for bearing with my ignorance here, I'm mainly a Python guy trying to grok Nim/C

**Comment by cheatfate** [comment]
`AddrInfo` structure is described here, but i dont think it helps you
https://github.com/nim-lang/Nim/blob/a879973081e2c29d64e9fb9d8e539aa980533b10/lib/posix/posix_linux_amd64.nim#L572-L581

It would be better for you to `man getaddrinfo`.

**Comment by blark** [comment]
Thank you for the information! The `getaddrinfo` man page is very helpful (I would have looked there first if I knew it was there).
